### ISSUE TITLE
HomeConMenu sometimes crashes in the background

### ISSUE THREAD

**Issue by Cykelero** [sonsongithub/HomeConMenu#13]
HomeConMenu seems to sometimes crash while I'm not using it. The crashes are silent: I don't get a crash reporting window.

However, [a crash report](https://www.cykeprojects.com/temp/2024-02-06/HomeConMenu-2024-02-04-214553.ips) does get generated in DiagnosticReports.

**Comment by sonsongithub** [comment]
I found a bug that may be the cause of the problem.
I will fix it in the next version.

**Comment by Cykelero** [comment]
After updating to 6.0.2 yesterday, the app crashed in the background again. The stack trace seems different from last time, though.
Here's [the report](https://www.cykeprojects.com/temp/2024-02-15/HomeConMenu-2024-02-15-073021.ips).

**Comment by Cykelero** [comment]
Sorry for the trouble!
I'd be happy to help diagnose. Tell me if there's something I can do to help find the issue.

I tried cloning the repo and building in Xcode, but package initialization fails: `could not find a branch named ‘fix-menuitem-leak’ in https://github.com/sonsongithub/KeyboardShortcuts.git`

**Comment by sonsongithub** [comment]
Fixed the package issue.

**Comment by Cykelero** [comment]
Thank you, the packages are being downloaded correctly, now.

I can't seem to build the app, whatever the target I choose, though; I get these errors. I understand if you don't have time to help me get through these, however!
![2024-02-27 14 19 Screenshot](https://github.com/sonsongithub/HomeConMenu/assets/2979318/ef0300d6-fdca-4ba6-bb77-de4d40315fad)

(I've selected “My Mac (Mac Catalyst)” as a target)

**Comment by Cykelero** [comment]
Thank you! The app builds and runs from Xcode on my Mac, now. Hopefully, if the crash happens, I'll be able to have a lot more details about what's happening.

**Comment by sonsongithub** [comment]
Thank you for your patient and support.

**Comment by Cykelero** [comment]
This hasn't happened in a long while, so let's assume the issue is fixed!
