### ISSUE TITLE
[ISSUE] wrong icon for "themed" smart sockets

### ISSUE THREAD

**Issue by Rastafabisch** [sonsongithub/HomeConMenu#4]
First off: I love your tool! If been search for something alike since quite some time, and even configured a workaround solution using the Shortcuts app. 

The minor issue I realised is, that sockets, which are configured to be lights (or fans I presume) within the Home app, are still displayed as sockets.

**Comment by sonsongithub** [comment]
Thank you, your report.
But, right now, I can not find the way to get the event when the icon is changed.
If I can find it, I would like to fix it.

**Comment by sonsongithub** [comment]
896703ca4a2586798b7707a85fc336df2e941848
