### ISSUE TITLE
[FEATURE REQUEST] global hotkeys (shortcuts) for devices & scenes

### ISSUE THREAD

**Issue by Rastafabisch** [sonsongithub/HomeConMenu#5]
The issues' name is pretty self explanatory. An UI for configuring global shortcuts. You might want to take a look at "[Scenecuts](https://github.com/nehayward/Scenecuts)" for some inspiration who this feature could look like.

**Comment by sonsongithub** [comment]
Thank you for your comment.

I'm currently investigating ways to support shortcuts. It appears that the architecture of HomeConMenu will have to be reworked to do so.
But, I'm interested in your request....

**Comment by sonsongithub** [comment]
I've already pushed the new version that supports global hotkeys.
If you can build it, please check out "develop" branch.

**Comment by sonsongithub** [comment]
I'm preparing to upload it Mac App Store.
