### ISSUE TITLE
[ISSUE] Memory leak on opening/closing MenuBar

### ISSUE THREAD

**Issue by Zer0x00** [sonsongithub/HomeConMenu#8]
Every time the menu bar list is opened and closed, the memory usage increases (and is never released again).  
I don't know if this is the only memory leak, as I don't open and close it enough for it to be a gigabyte like it is now:
<img width="737" alt="SCR-20231121-cach" src="https://github.com/sonsongithub/HomeConMenu/assets/32687653/87ac2ecc-5ac3-4449-b34f-d11329080790">

**Comment by sonsongithub** [comment]
Thank you.

I have checked memory usage of HomeConMenu.
I have identified a problem that may be a bit of a memory leak by Activity Monitor.app.

But, using Instruments.app, I could not find that my code was causing a memory leak.
I'll do some more investigation.

**Comment by sonsongithub** [comment]
Thank you for your reporting.
I've found my bugs and started to release the new version.

**Comment by sonsongithub** [comment]
How about new version, 3.1.3?

**Comment by Zer0x00** [comment]
I have version 4.0.1 (don't know where this comes from) but the issue seems fixed. Thanks you!
