### ISSUE TITLE
No devices despite enabling HomeKit access

### ISSUE THREAD

**Issue by jordank195** [sonsongithub/HomeConMenu#9]
Running Sonoma 14.0 and HomeCon 3.1.1. No devices are discovered. Tried reloading and disabling and reenabling HomeKit access.
<img width="167" alt="Screenshot 2023-11-26 at 18 21 11" src="https://github.com/sonsongithub/HomeConMenu/assets/17218306/8449e4af-3813-40b9-b7c6-0b8fea74da9b">
<img width="491" alt="Screenshot 2023-11-26 at 18 20 58" src="https://github.com/sonsongithub/HomeConMenu/assets/17218306/904c18eb-7656-4503-a4e7-f32144d39991">

**Comment by jordank195** [comment]
Updated to Sonoma 14.1.1 and the issue persists.

**Comment by sonsongithub** [comment]
How about version 3.1.3?

**Comment by jordank195** [comment]
I believe it's working. However, I have two homes in HomeKit. Only the devices from one home show up?

**Comment by sonsongithub** [comment]
Oh...
I didn't think too much about those cases.
I will see how to implement it ...............
#11
